// examples/client-js-headlessui-react/src/App.jsx
import { Fragment, useEffect, useState } from 'react';
import { Combobox, Transition } from '@headlessui/react';
import { CheckIcon, ChevronUpDownIcon, MapPinIcon } from '@heroicons/react/24/solid';
import placekit from '@placekit/client-js/lite';

// Make sure to call `placekit` outside of a component’s render to avoid
// recreating the `PlaceKit.Client` object on every render.
const pk = placekit(import.meta.env.VITE_PLACEKIT_API_KEY, {
  countries: ['fr'],
});

const App = () => {
  const [value, setValue] = useState('');
  const [suggestions, setSuggestions] = useState([]);

  useEffect(
    () => {
      pk.search(value).then((res) => {
        setSuggestions(res.results);
      });
    },
    [value]
  );

  return ( 
    <div className="fixed top-16 w-72">
      <Combobox value={value} onChange={setValue}>
        <div className="relative mt-1">
          <div className="relative w-full cursor-default overflow-hidden rounded-lg bg-white text-left shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-teal-300 sm:text-sm">
            <Combobox.Input
              className="w-full border-none py-2 pl-3 pr-10 text-sm leading-5 text-gray-900 focus:ring-0"
              onChange={(event) => setValue(event.target.value)}
            />
            <Combobox.Button className="absolute inset-y-0 right-0 flex items-center pr-2">
              <ChevronUpDownIcon
                className="h-5 w-5 text-gray-400"
                aria-hidden="true"
              />
            </Combobox.Button>
          </div>
          <Transition
            as={Fragment}
            leave="transition ease-in duration-100"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <Combobox.Options className="absolute mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
              {suggestions.length === 0 && value !== '' ? (
                <div className="relative cursor-default select-none py-2 px-4 text-gray-700">
                  Nothing found.
                </div>
              ) : suggestions.map((item) => {
                const val = [
                  item.name,
                  item.zipcode,
                  item.city
                ].join(' ');
                return (
                  <Combobox.Option
                    key={item.id}
                    value={val}
                    className={({ active }) =>
                      `relative cursor-default select-none py-2 pl-10 pr-4 ${
                        active ? 'bg-teal-600 text-white' : 'text-gray-900'
                      }`
                    }
                  >
                    {({ selected, active }) => (
                      <>
                        <span
                          className={`block truncate ${
                            selected ? 'font-medium' : 'font-normal'
                          }`}
                        >
                          {val}
                        </span>
                        <span
                          className={`absolute inset-y-0 left-0 flex items-center pl-3 ${
                            active ? 'text-white' : 'text-gray-300'
                          }`}
                        >
                          {selected ? (
                            <CheckIcon className="h-5 w-5" aria-hidden="true" />
                          ) : (
                            <MapPinIcon className="h-5 w-5" aria-hidden="true" />
                          )}
                        </span>
                      </>
                    )}
                  </Combobox.Option>
                );
              })}
            </Combobox.Options>
          </Transition>
        </div>
      </Combobox>
    </div>
  );
};

export default App;

// examples/client-js-headlessui-vue/src/App.vue
<template>
  <div class="fixed top-16 w-72">
    <Combobox v-model="selected">
      <div class="relative mt-1">
        <div class="relative w-full cursor-default overflow-hidden rounded-lg bg-white text-left shadow-md focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-opacity-75 focus-visible:ring-offset-2 focus-visible:ring-offset-teal-300 sm:text-sm">
          <ComboboxInput
            class="w-full border-none py-2 pl-3 pr-10 text-sm leading-5 text-gray-900 focus:ring-0"
            @change="search($event.target.value)"
          />
          <ComboboxButton
            class="absolute inset-y-0 right-0 flex items-center pr-2"
          >
            <ChevronUpDownIcon class="h-5 w-5 text-gray-400" aria-hidden="true" />
          </ComboboxButton>
        </div>
        <TransitionRoot
          leave="transition ease-in duration-100"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
          @after-leave="state.query = ''"
        >
          <ComboboxOptions class="absolute mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
            <div
              v-if="state.suggestions.length === 0 && value !== ''"
              class="relative cursor-default select-none py-2 px-4 text-gray-700"
            >
              Nothing found.
            </div>

            <ComboboxOption
              v-for="item in state.suggestions"
              as="template"
              :key="item.id"
              :value="[item.name, item.zipcode, item.city].join(' ')"
              v-slot="{ selected, active }"
            >
              <li
                class="relative cursor-default select-none py-2 pl-10 pr-4"
                :class="{
                  'bg-blue-500 text-white': active,
                  'bg-white text-black': !active
                }"
              >
                <span
                  class="block truncate"
                  :class="{ 'font-medium': selected, 'font-normal': !selected }"
                >
                  {{ [item.name, item.zipcode, item.city].join(' ') }}
                </span>
                <span
                  class="absolute inset-y-0 left-0 flex items-center pl-3"
                  :class="{ 'text-white': active, 'text-gray-300': !active }"
                >
                  <CheckIcon v-if="selected" class="h-5 w-5" aria-hidden="true" />
                  <MapPinIcon v-else class="h-5 w-5" aria-hidden="true" />
                </span>
              </li>
            </ComboboxOption>
          </ComboboxOptions>
        </TransitionRoot>
      </div>
    </Combobox>
  </div>
</template>

<script setup>
  import { reactive } from 'vue';
  import {
    Combobox,
    ComboboxInput,
    ComboboxButton,
    ComboboxOptions,
    ComboboxOption,
    TransitionRoot,
  } from '@headlessui/vue';
  import { CheckIcon, ChevronUpDownIcon, MapPinIcon } from '@heroicons/vue/24/solid';
  import placekit from '@placekit/client-js/lite';

  const pk = placekit(import.meta.env.VITE_PLACEKIT_API_KEY, {
    countries: ['fr'],
  });

  const state = reactive({
    query: '',
    suggestions: [],
  });

  function search(query) {
    state.query = query;
    pk.search(query).then((res) => {
      state.suggestions = res.results;
    });
  }
</script>
